### ISSUE TITLE
Put the base of the backend in place

### ISSUE THREAD

**Issue by NewLunarFire** [FDS-CODEVID19/backend#1]
With the following components:

- Flask
- SQL Alchemy
- Flask-Migrate
- Flaggser or Flask-rebar
- Black

**Comment by nscharrenberg** [comment]
- [x] Flask initialized
- [x] Basic directory structured implemented
- [x] Black implemented
- [x] basic test structure added
- [x] SQL Alchemy added
- [ ] OpenAPI Implementation (Flaggser or Flask-rebar)
- [ ] Flask-Migrate implemented
