### ISSUE TITLE
Login and logout routes

### ISSUE THREAD

**Issue by NewLunarFire** [FDS-CODEVID19/backend#2]
Create a POST /login route that receives the following payload and returns 200 on success, or 403 on failure:
```json
{
  "username": "username",
  "password": "password"
}
```

**Comment by halfacat1** [comment]
@nscharrenberg @NewLunarFire Please add me to the team. Thanks!

**Comment by nscharrenberg** [comment]
A logout route doesn't seems to be beneficial for the prototype, as we aren't doing anything with token invalidation. I think it would be better to look at it once it's actually needed.
