### ISSUE TITLE
Environmental Variables

### ISSUE THREAD

**Issue by nscharrenberg** [FDS-CODEVID19/backend#6]
**Is your feature request related to a problem? Please describe.**
Currently everything is still hardcoded into a `config.py`. Currently no credentials are being stored, but in the future email or database credentials will be used, and shouldn't be hardcoded in the code.

**Describe the solution you'd like**
Make use of environmental variables, packages such as python-dotenv could be implemented for the storage of environmental variables.

**Additional context**
Make sure that environmental files such as `.env` which is being used by the server, is NOT being commited to the repository, while the example environment file such as `.env.example` SHOULD be commited to the repository.

**Comment by adace123** [comment]
@nscharrenberg I can take this one.
