### ISSUE TITLE
Test Environment

### ISSUE THREAD

**Issue by nscharrenberg** [FDS-CODEVID19/backend#7]
**Describe the bug**
Testing is currently happening on the development environment, while it should be done in a test environment.

**To Reproduce**
1. run `python -m unittest discover test` and notice it being written to the `app/app.db`.

**Expected behavior**
When running `python -m unittest discover test`, a seperate sqlite database should be created called similar to `app/test.db`, the development environment isn't affected by created test and vise versa.

**Comment by adace123** [comment]
I can take this one
